// Add new lines here any time — just add another string to this array,
// one sentence per entry. No other code needs to change.
const SENTENCES = [
  "WOI WOI WOI",
  "START POSTING",
  "RAYDEN ANGRY LIAO",
  "EH",
  "I CAME ALL THE WAY FROM CHINA ON TWO BICYCLE WHEEL TO SEE THIS",
  "🏞️ IS THIS A PARK OR A PLAYGROUND??",
  "AYD!!!",
  "U THINK WE SCOLD U VV HAPPY AH",
  "📢 *YALL KNOW PPL LEAVING CAUSE YALL SPAM EVERYDAY AND CHAT IS TAKING UP AROUND 1 - 10GB*",
  "SON",
  "WAH",
  "HOW ARE THERE RARITIES-",
  "SHUCKS",
  "6583774280@s.whatsapp.net using bot for a few months and no bans (the only ban is when he added 100+ ppl in a gc)",
  "JSON",
  "SQL",
  "JS",
  "TS",
  "SONION RING",
  "Record of the day",
  "YALL SPAM ONE MORE TIME LAH, I WILL SPAM THROW YOU GUYS INTO LONGKANG",
  "NONSENSE",
  "📢 *YALL SPAM SOMEMORE WE BAN YALL FROM BOT YOU WANT?*",
  "WHAT IS THIS",
  "ASH",
  "WELCOME ONBOARD OF ASH AIRLINE",
  "THIS TRAIN SERVICE ENDS HERE, ALL PASSENGERS PLEASE ALIGHT. THANK YOU FOR TRAVELLING WITH SMRT.",
  "*WHO YOU THINK YOU ARE!?*",
  "A friendly reminder to stay hydrated! Drink more water to keep yourself healthy. 💧",
  "SPAM SUMMORE",
  "HATS TO BREAK IT TO YALL, BUT THIS ISNT HARRY'S WORLD OK",
  "EH COME BRO",
  "📢 *YALL JUST NOW REACT WHY NOW NO REACT YALL SCARED RIGHT!?*",
  "ILY",
  "LET ME COOK",
  "HEYYYY",
  "YOU SCARED IT IS!?",
  "ARGHHHHHHH I KEEP SPELLING HATE WRONG AHHHHHHHH",
  "MAC AND CHEESE BANGBANG SAUCE",
  "Chicken chop",
  "Cai fan",
  "Muffin",
  "niu rou mian",
  "BARIS, SEDYIA",
  "Stop making me feel like a 懒惰的屁股",
  "cuz the whole clase call me XMM",
  "Stop fooling around like crowns doing a stupid show",
  "IS THIS A FISH MARKET (Slaps the wallet on the ground)",
  "I went to new york, walk over water with nothing but my bare feet",
  "DO I MAKE MYSELF CLEAR!?",
  "I WENT TO CHINA (WITH TWO BICYCLE WHEELS)",
  "Next station, Jurong East",
  "DOORS ARE CLOSING",
  "SMRT",
  "what the actual shucks bro",
  "I SUMMON RAYDEN DEN YALL KNOW",
  "SPAM SUMMORE SPAM SUMMORE",
  "YALL 把我们的话当成耳边风",
  "TELL YALL PAY ATTENTION IN CLASS, GO STUDY",
  "ARE YOU GUYS ILLITERATE OR JUST PLAIN STUPID",
  "DON'T UNDERSTAND SIMPLE ENGLISH AH",
  "I TELL YALL STOP SPAMMING HOW MANY TIMES ALREADY",
  "OI OI OI",
  "SHUT UP U DING DOING",
  "うるさい",
  "こんにちは",
  "This video is sponsored by our sponsor, who, as you may have already correctly and undoubtedly assumed, is in fact the sponsor of this very video that you are currently watching. Yes, you heard that right: the sponsor sponsoring this video is none other than the sponsor who has sponsored this video, making them, by definition, the official sponsor of this sponsored video.Now, you might be wondering: “Who exactly is sponsoring this video?” Well, I’m glad you asked, because the answer is incredibly important and absolutely worth repeating: the sponsor is the sponsor of the video. And who sponsored the sponsor? Nobody, because the sponsor is already the sponsor. And what did they sponsor? This video. Which video? This video. The very video in which we are currently talking about the sponsor who sponsored the video.So, to recap: this video has a sponsor. That sponsor is sponsoring the video. The sponsor of the video is therefore the sponsor, and the video is sponsored by that sponsor. This means that the sponsor is, in fact, sponsoring the sponsored video that they are the sponsor of.And with that incredibly important clarification out of the way, and now that we have established beyond any reasonable doubt that the sponsor of this video is indeed the sponsor sponsoring this video, let’s finally stop talking about the sponsor sponsoring the video and continue with the actual video.",
  "GOOD BOY",
  "GOOD GIRL"
];

module.exports = {
  name: "ash",
  description: "Says something random",
  async execute(ctx) {
    const line = SENTENCES[Math.floor(Math.random() * SENTENCES.length)];
    await ctx.sendText(line);
  },
};
