// Add new lines here any time — just add another string to this array,
// one sentence per entry. No other code needs to change.
const SENTENCES = [
  "WOI WOI WOI",
  "START POSTING",
  "RAYDEN ANGRY LIAO",
  "EH",
  "I CAME ALL THE WAY FROM CHINA ON TWO BICYCLE WHEEL TO SEE THIS",
  "🏞️ IS THIS A PARK OR A PLAYGROUND??",
  "AYD!!!",
  "U THINK WE SCOLD U VV HAPPY AH",
  "📢 *YALL KNOW PPL LEAVING CAUSE YALL SPAM EVERYDAY AND CHAT IS TAKING UP AROUND 1 - 10GB*",
  "SON",
  "WAH",
  "HOW ARE THERE RARITIES-",
  "SHUCKS",
  "6583774280@s.whatsapp.net using bot for a few months and no bans (the only ban is when he added 100+ ppl in a gc)",
  "JSON",
  "SQL",
  "JS",
  "TS",
  "SONION RING",
  "Record of the day",
  "YALL SPAM ONE MORE TIME LAH, I WILL SPAM THROW YOU GUYS INTO LONGKANG",
  "NONSENSE",
  "📢 *YALL SPAM SOMEMORE WE BAN YALL FROM BOT YOU WANT?*",
  "WHAT IS THIS",
  "ASH",
  "WELCOME ONBOARD OF ASH AIRLINE",
  "THIS TRAIN SERVICE ENDS HERE, ALL PASSENGERS PLEASE ALIGHT. THANK YOU FOR TRAVELLING WITH SMRT.",
  "*WHO YOU THINK YOU ARE!?*",
  "A friendly reminder to stay hydrated! Drink more water to keep yourself healthy. 💧",
  "SPAM SUMMORE",
  "HATS TO BREAK IT TO YALL, BUT THIS ISNT HARRY'S WORLD OK",
  "EH COME BRO",
  "📢 *YALL JUST NOW REACT WHY NOW NO REACT YALL SCARED RIGHT!?*",
  "ILY",
  "LET ME COOK",
  "HEYYYY",
  "YOU SCARED IT IS!?",
  "ARGHHHHHHH I KEEP SPELLING HATE WRONG AHHHHHHHH",
  "MAC AND CHEESE BANGBANG SAUCE",
  "Chicken chop",
  "Cai fan",
  "Muffin",
  "niu rou mian",
  "BARIS, SEDYIA",
  "Stop making me feel like a 懒惰的屁股",
  "cuz the whole clase call me XMM",
  "Stop fooling around like crowns doing a stupid show",
  "IS THIS A FISH MARKET (Slaps the wallet on the ground)",
  "I went to new york, walk over water with nothing but my bare feet",
  "DO I MAKE MYSELF CLEAR!?",
  "I WENT TO CHINA (WITH TWO BICYCLE WHEELS)",
  "Next station, Jurong East",
  "DOORS ARE CLOSING",
  "SMRT",
  "what the actual shucks bro",
  "I SUMMON THE RAYDEN DEN YALL KNOW",
  "SPAM SUMMORE SPAM SUMMORE",
  "YALL 把我们的话当成耳边风",
  "TELL YALL PAY ATTENTION IN CLASS, GO STUDY",
  "ARE YOU GUYS ILLITERATE OR JUST PLAIN STUPID",
  "DON'T UNDERSTAND SIMPLE ENGLISH AH",
  "I TELL YALL STOP SPAMMING HOW MANY TIMES ALREADY",
  "OI OI OI",
  "SHUT UP U DING DOING",
  "うるさい",
  "こんにちは",
  "This video is sponsored by our sponsor, who, as you may have already correctly and undoubtedly assumed, is in fact the sponsor of this very video that you are currently watching. Yes, you heard that right: the sponsor sponsoring this video is none other than the sponsor who has sponsored this video, making them, by definition, the official sponsor of this sponsored video.Now, you might be wondering: “Who exactly is sponsoring this video?” Well, I’m glad you asked, because the answer is incredibly important and absolutely worth repeating: the sponsor is the sponsor of the video. And who sponsored the sponsor? Nobody, because the sponsor is already the sponsor. And what did they sponsor? This video. Which video? This video. The very video in which we are currently talking about the sponsor who sponsored the video.So, to recap: this video has a sponsor. That sponsor is sponsoring the video. The sponsor of the video is therefore the sponsor, and the video is sponsored by that sponsor. This means that the sponsor is, in fact, sponsoring the sponsored video that they are the sponsor of.And with that incredibly important clarification out of the way, and now that we have established beyond any reasonable doubt that the sponsor of this video is indeed the sponsor sponsoring this video, let’s finally stop talking about the sponsor sponsoring the video and continue with the actual video.",
  "GOOD BOY",
  "GOOD GIRL",
  "Max Verstappen wins the ASH grand prix!",
  "my admin bu jian le",
  "AHEM",
  "Want a break from the ads? If you tap now to watch a short video you'll get 30 minutes of ad free music! Yes, really! If you tap now you'll get 30 minutes of ad free music! So what are you waiting for? I'm still waiting.. Why aren't you tapping? Don't you want 30 minutes of ad free music? If you tap now and watch the short video you'll get 30 minutes of ad free music! It's that easy! If you want to be free from the ads forever consider buying spotify premium! With spotify premium, you get ad free music, forever! And if you tap below you can get the first 3 months for free! Terms and Conditions apply",
  "BRO I SAW A FLASH",
  "!ash",
  "BROSKI",
  "bro",
  "In the universe, we have the atmosphre, exosphere, lithosphere and biosphere. But losing you is my biggestsphere.",
  "Are you made out of Copper and Tellerium? Cuz you’re made cute.",
  "Can you be element Br but without the Bro?",
  "MAJULAH SINGAPURAAA",
  "Senpaiiiiiiiii~",
  "Kohaiiiiiii~~",
  "*SON* PHU QUOC AIRWAYS",
  "REPUBLIC OF *SON* GAPORE AIR FORCE",
  "*SON* NILA UTAMA",
  "*SON* GAPORE",
  "*SON* GAPORE AIRLINES",
  "you’re not mine",
  "you're mine forever",
  "OI",
  "i ain’t gonna rizz u up cuz you’re not mine",
  "Spell out 'Biology'",
  "Dear passengers, in a few moments, we will arrive at: Cirebon station. If you end your trip at: Cirebon station, please prepare yourself and check your belongings. For your own safety, it is forbidden to open the train's door before the train completely stops. Thank you for choosing PT Kereta Api Indonesia. See you on the next trip. _KAI Train chime starts playing_",
  "'pinhed' 🥀 'pinhead'",
  "When theres a hole theres a goal",
  "LAAAAAAA AHHH AAAAAAHHHHH AH! LALALAAAAA LALALALALALALAAAAAA! OK DONE, I SING OPERA ALDY",
  "glaciers are large masses of ice that rest on land of float on sea",
  "*ARE YOU GUYS PURE STUPID OR HAVE NO GODDAMN MIND*",
  "*STOP SPAMMING IF NOT I WILL NUKE AND DELETE THIS GROUP*",
  "Ding dong, doors are closing, dun dun dun dun dun dun. Pshhhhhhh",
  "Make the impossible possible",
  "Literature. Yes or no?",
  "Weatger singapore",
  "GG FKCING EZ",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AYY AYY AYY I’m your little butterfly",
  "ASH SEDIA",
  "costal errosions happen when loose sediments are washed away by waves, tides or currents. The waves do not lose energy when they travel towards the coastal area. Coastal errosion will happen when the waves subsequently hit the coastal area.",
  "Te te te te te teto",
  "Yt post",
  "Can you be the equivalent anticlockwise moment to make me an equilibrium?",
  "HMPH",
  "Soil erosions happen when rainwater hits the ground at a considerable amount of force that separates soil particles. Wated cannot infiltrate through the soil and becomes surface runoff. Soil partciles are washed away WITH the water and cause major soil erosion.",
  "Lao ban, are you Spotify Premium? Because you’re worth paying attention to.",
  "eh Coolpilot you’re gonna write 800 more operas",
  "Chat suddenly went quiet",
  "60+ broski",
  "Sponsored by AEROHUB",
  "when shipping jay and ashleigh is alway 100%",
  "I was a girl in the village doing alright. Then I became a princess overnightt.",
  "Add posts from youtube",
  "i put too much soy sauce yeah",
  "we must respect the c151",
  "WAFFLES",
  "Plen news",
  "Haiiiiiiiii",
  "Tropical rainforests help to reduce soil erosion because the leaves and branches slow down the falling of water droplets. Water can infiltrate though the soil and it reduces soil erosion. The roots of the plant hold the soil firmly so the soil does not errode. This reduces the chances of soil errosion.",
  "U da real spotify",
  "Cough cough, ahem ahem",
  "HOW COME U DK",
  "SHUT THE AEROSHUCKINGSECURE UP",
  "when shipping xinyang and chun ning is alway 100%",
  "LIVE Flightradar tracking",
  "Mangroves help in reducing costal errosions because the roots of the plants help to trap and stabilise the loose sediements so they will not be washed away by tides, currents or waves. The trunks of the plants cause friction between the waves, thus making the waves lose energy wheh travelling towards the coastal area and it reduces the chances of coastal errosion",
  "Apt apt apt apt apt apt uh uh huh uh huh don’t you want me like I want you babyy don’t you need me like I need you nowww",
  "Monkey xi monkey jun",
  "Merry Christmas everyone",
  "Oceans are large masses of water",
  "NI HOWDY",
  "'I am just gonna put my foot on the floor, and I am not lifting until I see God or checkered flag'-Hail Melon",
  "WADDASHUCKITYSHUCKSSHUCKSTOTHEMAXMAN AHHHH",
  "ONE SHOT LOW HP GG FCKING EZ",
  "ASH FALL IN",
  "School faster finish, I faster ciao"
  ];

module.exports = {
  name: "ash",
  description: "Says something random",
  async execute(ctx) {
    const line = SENTENCES[Math.floor(Math.random() * SENTENCES.length)];
    await ctx.sendText(line);
  },
};
