// Word lists for !wordle (lib/wordle.js).
//
// ANSWERS: common, everyday 5-letter English words — the secret word is always one of these.
// VALID:   every 5-letter word accepted as a guess (the answers plus a larger set of real words).
// Both are lowercase. They were built from an English dictionary filtered by how
// common each word is, with names, places, brands and a few unsuitable words removed.
// Add or remove words freely — just keep them lowercase, 5 letters, separated by spaces/newlines.

const ANSWERS = `
about their there which would other after first think could these where right being going still
never those world great while every state three since under thing house place again found might
money night until doing group women start today point music power water based small white later
order party thank using black whole maybe story least early local video young court given level
often death south known large wrong along class close cause human woman leave north watch light
short taken third among check heart asked child media phone quite final front ready bring heard
march study clear month board field fight force issue space total above share sense break event
sorry guess learn added alone movie press tried sound value round stand stuff drive green match
model trust range trade chief lower style blood stage title enjoy cover legal seven staff super
began built crazy daily paper voice whose earth below offer sleep table truth build piece visit
wrote river shall speak write album eight funny peace spent store track ahead allow brown moved
radio cross loved speed extra quick agree clean photo scene spend coach heavy train claim hotel
judge named brain floor image meant reach civil dance stock worst beach ended older color dream
grand sweet touch doubt drink shown basic crime fully plant worse award block lived avoid catch
coast trial truly queen broke glass prior serve begin twice worry count fresh mouth owner scale
score smart throw click metal agent apply enter prime waste weird adult grade stone apart aware
fifth proud birth labor prove tough alive apple dress horse liked magic owned stick guide raise
treat youth exist guard shoot solid sport taste hello plane shape upper cheap joint steel tired
crowd enemy fixed limit ocean proof chair noted email stuck sugar drama entry grown lying route
saved smoke squad teach angry laugh lunch actor chain equal quiet split fault mixed phase smile
truck blame dying false fired novel shirt cream giant minor theme usual voted draft spoke upset
cycle armed aside empty prize rural admit favor frame guest teeth bunch fruit index shift stood
tight crown chose crash depth dirty error noise panel plate shame cable print sight broad drawn
motor solar blind brief chest debut paint pilot steam exact quote swear trend bread inner reply
tower wheel faced filed pride rough smell topic sharp trick audio chart mount occur argue awful
bound cloud loose moral shock thick threw flash gross refer trail uncle badly ideal clock label
pitch pizza plain anger comic ghost newly skill solve trash boost crack hired knife saint steal
delay elite forth layer nurse rugby sheet bench medal silly angle forum grass hence rapid sixth
valid vital creek fraud ratio scary spell sword begun daddy drove juice logic strip dozen input
knock ought flood rally swing alert arena brave fleet shake shore blast pound punch fewer grave
mouse piano slave craft devil rated ruled sauce slide tiger alien beast cited dated fifty relax
acted alarm globe hoped spare opera quest sized lover panic scope aimed alpha brick outer screw
venue habit naval robot toxic wider wound asset baker brush essay maker snake ultra usage canal
climb fever fluid nasty twist unity blown fence stole bored dealt flesh forty hated laser loyal
patch radar villa adopt blade cargo cried humor nerve sheep chill grain liver rifle rival sadly
slept spray suite verse bless couch crush genre lease shine tweet react shade vocal yield bacon
burst salad stake swift awake blank curve harsh hurry organ sweat alike arrow cabin eagle eaten
guilt theft valve charm cruel delta ridge tribe canon cared stamp voter witch array belly booth
fatal lemon shark dairy diary drill meter safer skull smash basin breed chick fairy freak grief
lined lodge merit micro rebel tooth viral widow beard curse drain flame ninth petty reign scare
cheat cheer demon elder fiber fried pulse realm shout alter brass graph shook stack aging audit
dried burnt buyer cease cloth eager elect lobby orbit ranch trunk badge ferry gauge rider shelf
width loser sheer stark thumb urged wheat wrist acute civic clerk crude drone flour pause puppy
slice vinyl probe sneak spark steep straw weigh adapt dense whale ankle armor clash grasp handy
poker scout steak sweep tumor cheek curry polar skirt toast waist wreck blend brake cough depot
drank feast frost purse tense chess float grind hobby newer risky sided sober spice swept towel
arise bloom clown dodge guild prone siege sixty sonic spine baked crane donor pasta tenth batch
paste plaza stare blunt champ ditch scrap shaft slope snack stiff sworn unite vault wagon midst
onion rogue choir karma shiny spoon thief bully messy ninja roast salon tuned vague dough hardy
irony maple relay risen niche porch utter creep elbow exile grill ruler spill swamp tasty decay
flown imply reset shave drift hatch niece scent slate surge token yacht manor pupil spoil altar
combo flush ounce seize spicy wired stall strap disco faint forge notch queue trout crawl digit
jelly lunar peach tesla cedar dunno metre pinch queer rover syrup congo dwarf liner merge moron
naive opted rigid vivid aided boxer cured hedge joker laden rainy salty serum skate stray tempo
torch turbo arose blink chang chili excel faded glove greed greet negro owing proxy renew retro
rumor stoke thigh troll aisle amino bleed brace choke motto onset pixel prose razor steer ample
bingo cubic ebook macro shady slack slick stove tract vista vogue creed crisp crust fined gamma
grape juicy moody prank spear stain tidal wrath blaze chalk flock hyper moist scoop scrub shale
titan trait troop clone drown obese scarf sushi timer tying borne fibre focal noisy snail tutor
yeast erase manly oxide pence repay rouge shove booze chord crest decor fetch fuzzy nicer optic
panda slash stein baton chunk cocoa comet dread dummy flank flare forex lever pedal query sewer
smack swell align attic await cache comfy condo flick funky groom hydro lyric plead debit
`.split(/\s+/).filter(Boolean);

const VALID = new Set(
  `
aarti aback abate abaya abbas abbey abbot abhor abide abies abled abode abort about above abram
abuse abuts abuzz abyss ached aches acids acing acker acorn acres acrid acted actin acton actor
acute adage adapt added adder adept adieu adios admin admit adobe adobo adopt adore adorn adult
aedes aegis aeons aerie affix afire afoot afore afoul after again agape agate agave agent agers
agger aggie aggro agile aging aglow agony agora agree ahead ahold aided aides aight aimed aimer
aioli aired aisle akita alamo aland alans alarm albee album alder aleck aleph alert algae algal
alias alibi alien align alike aline alive aliya alkyl allay allee alley allis allot allow alloy
allyl almas aloft aloha alone along aloof aloud alpha altar alter altho altos alums alway amass
amaze amber ambit amble ameer amend amici amide amiga amigo amine amino amiss amity amman ammon
among amour amped ample amply amrit amuck amuse anata andro anent angel anger angle anglo angry
angst anima anime anion anise anker ankle annas annex annoy annul anode antar antes antic antis
antsy anvil aorta apace apart apgar aphid aphis aping apnea appel apple apply apres apron aptly
arbor arcos ardor areal areas arena argan argon argue argus arias ariel arise arish arles armed
armor aroma arose arras array arris arrow arsed arses arson artic artis artsy asana ascot ashen
ashes aside asked asker askew aspen aspic assam assay asses asset aster atlas atman atoll atoms
atone atria attar attic audio audit auger aught augur aunts aunty aural auras auric aurum autos
auxin avail avant avast avert avian avoid await awake award aware awash aways awful awoke axial
axils axing axiom axles axons ayres azide azure babel babes bacca bacha backs bacon badge badly
bagel baggy bails bairn baits bajan baked baker bakes baldy baler bales balks balls bally balms
balmy baloo balsa balti bambi banal banco banda bandh bands bandy banes bangs banjo banks banns
bantu barbe barbs barca bardo bards bared bares barge barks barmy barns baron barra barre barro
barry basal based baser bases basho basic basil basin basis basse bassi basso basta baste basti
batch bated bates bathe baths batik baton batts batty baulk bawdy bayes bayou bazar beach beads
beady beaks beams beano beans beard bears beast beats beaty beaut beaux bebop becks beech beefs
beefy beeps beers beery beets befit began begat beget begin begum begun beige being belay belch
belie belle bells belly below belts bench bends bendy benes benet benny bento beret berks berms
berry berth beryl beset bests betas betel betta betty bevel bezel bible bicep biddy bidet biffy
biggs biggy bight bigly bigot bijou biked biker bikes bilbo biles bilge bills billy bimbo bindi
binds binge bingo binks biome biota biped bipod birch birds birks birth bison bitch biter bites
bitsy bitte bitty black blade blain blame bland blank blare blart blase blast blatt blaze bleak
bleat bleed bleep blend bless blest blimp blind bling blink blips bliss blitz bloat blobs block
blocs blogs bloke blond blood bloom bloop blots blown blows blued bluer blues bluey bluff blume
blunt blurb blurs blurt blush board boars boast boats bobby bocce bodes bodhi boeuf bogan bogey
boggy bogie bogle bogus boils boing bokeh bolas boles bolts bolus bombs bonds boned boner bones
boney bongo bongs bonne bonny bonus boobs booby booed books booms boons boost booth boots booty
booze boozy boras borax bored borel borer bores borgo boric borne boron bosom boson bossy botch
bothy bough boule boult bound bourg bourn bouts bowed bowel bower bowes bowie bowls boxed boxer
boxes bozos braai brace brach brack braes brags braid brain brake brand brane brant brash brass
brats brava brave bravo brawl brawn bread break bream breds breed brees brent breve brews briar
bribe brick bride brief brier brill brims brine bring brink briny brisk brits britt broad broch
brock broil broke brome bromo bronc brood brook broom broth brown brows bruin brule brung brunt
brush brute bubba bubby bucko bucks buddy budge buffs buffy buggy bugle build built bulbs bulge
bulky bulla bulls bully bumps bumpy bunce bunch bundt bundy bunks bunny bunty buoys burbs burgh
burka burke burks burly burns burnt burps burqa burro burrs burry bursa burst busby bused buses
bushy busts busty butch butte butts butyl buxom buyer buzzy bylaw bytes byway cabal cabin cable
cacao cache cacti caddy cadet cadre cafes caged cages cagey caird cairn cajon cajun caked cakes
cakey calif calla calls calms calyx camas camel cameo campo camps campy camus canal candy caned
canes canna canny canoe canon canst canto caped caper capes capex capon caput carat carbo carbs
cardi cards cared carer cares carex cargo carle carob carol caron carpi carry carta carte carts
carve casas casco cased cases casks caste casts casus catch cater cates catty caulk causa cause
caved caves cavil cease cedar ceded cedes celeb cella cello cells celts cento cents ceres certs
chace chaco chafe chaff chain chair chalk champ chana chang chant chaos chaps chara chard charm
chars chart chase chasm chats chavs chaya cheap cheat check cheek cheep cheer chefs chemo chert
chess chest chevy chews chewy chiao chica chick chico chide chief child chile chili chill chime
chimp china chine chink chino chins chips chiro chirp chive chock choco chode choir choke chola
cholo chomp chook choon chops chord chore chose chota choux chowk chubs chuck chugs chump chums
chunk churn chute cider cigar cilia cinch circa cisco cissy cited cites civet civic civil clack
clade claes claim clamp clams clang clank clans claps claro clary clash clasp class clave claws
clays clean clear cleat cleft clerk cleve click cliff clift climb cline cling clink clint clips
cloak clock clods clogs cloke clone close cloth clots cloud clout clove clown clubs cluck clued
clues clump clung clunk coach coals coast coats cobbs coble cobra cocks cocky cocoa cocos codec
coded coder codes codex codon coffs cohen coils coins coked cokes colas colby colds coles coley
colic colin colon color colts comas combe combi combo combs comer comes comet comfy comic comix
comma comms compo comps comte conch condo cones coney conga congo conic conte conus convo cooch
cooed cooks cools coons coops coots copay coped copes copra copse coral coram corby cords cored
cores corey corgi corks corky corns corny corps corse corso costa coste costs cotes cotta couch
cough could count coupe coups cours court coven cover coves covet covey cowan cowed cower coyly
crabs crack craft crags craic craig cramp crane crank craps crash crass crate crave crawl craze
crazy creak cream credo creds creed creek creel creep creme crepe crept cress crest crewe crews
cribs crick cried crier cries crime crimp crisp croak crock crocs croft crone cronk crony crook
croon crops crore cross croup crowd crown crows crude cruel crumb crump crunk cruse crush crust
crypt cubby cubed cubes cubic cubit cuddy cuffs culex culls cully culpa cults cumin cunts cupid
cuppa curbs curds cured cures curia curie curio curls curly curry curse curve curvy cushy cusps
cutch cuter cutie cutty cyber cycle cyclo cynic cysts czars dacha daddy daffy daily dairy daisy
dales dally daman dames damme damns dance dancy dandy danks danny darcy dared dares darks darts
dashi dated dates datum daunt dawah dawns dayan dazed deads deals dealt deans dears deary death
debby debit debts debug debut debye decaf decal decay decks decor decoy decry deeds deems deeps
deere deers deets defer deffo degas deign deism deist deity delay delft delis dells delly delos
delph delta delve demon demos denim denis dense dents deoxy depot depth derby derma derry desks
deter detox deuce devas devel devil devon dewan dewar dhoti dials diane diary diced dices dicey
dicks dicky dicta diddy didst diene diets digit dikes dildo dilly dimer dimes dimly dinar dined
diner dines dingo dings dingy dinks dinky dinna dinos diode dippy dirge dirks dirty disco discs
disks ditch ditto ditty ditzy divan divas dived diver dives divot divvy diwan dixie dixit dizzy
djinn dobby dobie dobro docks dodge dodgy doers doest doeth doggo doggy dogma doily doing dolce
doled doles dolls dolly dolor domed domes doner dongs donna donne donny donor donut doody dooms
doors doozy doped dopes dopey doric doris dorks dorky dorms dosed doses doted dotes dotty doubt
douce dough doula douma douse dover doves dowdy dowel dower dowie downs downy dowry doyen dozed
dozen dozer draco draft drags drain drake drama drams drank drape drawl drawn draws dread dream
dregs dress dried drier dries drift drill drink drips drive droid droit droll drone drool droop
drops dross drove drown drugs druid drums drunk dryad dryer dryly duals dubbo ducal duchy ducks
ducky ducts duddy dudes duels duets dukes dulls dumas dumbo dummy dumps dumpy dunce dunes dungy
dunks dunno duomo duped duper dupes dural duras durst durum dusky dusts dusty dutch duvet dwarf
dweeb dwell dwelt dyers dying dykes eager eagle eared earls early earns earth eased easel eases
easts eaten eater eaves ebbed ebony ebook echos edema edged edges edict edits eerie effed egged
egger egret eider eight eject eland elbow elder elect elegy elfin elite elope elude elves emacs
email embed ember emcee emery emits emmer emmet emmys emote empty enact ended ender endow enema
enemy enjoy ennui enrol ensue enter entry envoy epics epoch epoxy equal equip erase erect ergot
erica erick erode erred error erupt essay ester ether ethic ethos ethyl etude euros evade evens
event evert every evict evils evoke exact exalt exams excel execs exert exile exist exits exons
expat expel expos extol extra exude eying eyrie fable faced faces facet facts faded fader fades
faery fagin fails faint fairs fairy faith faked faker fakes fakir falls false famed fancy fangs
fanny fanon farce fared fares farms farts fasti fasts fatal fated fates fatso fatty fatwa fault
fauna faves favor fawns faxed faxes fayed fayre fazed fears feast feats fecal feces fedex feeds
feels feign feint feist fella fells felon felts femme femur fence fends feral feria fermi ferns
ferry festa fests fetal fetch feted fetes fetid fetus feuds fever fewer fiber fibre fibro ficus
fides fiefs field fiend fiers fiery fifth fifty fight filed filer files filet fille fills filly
films filmy filth final finca finch finds fined finer fines finis finks fired fires firms first
firth fishy fists fitch fitts fiver fives fixed fixer fixes fizzy fjord flack flags flail flair
flake flaky flame flank flaps flare flash flask flats flava flaws fleas fleck flees fleet flesh
flick flied flier flies fling flint flips flirt flits float flock floes flood floor flops flora
flory floss flour flout flown flows fluff fluid fluke flume flung flunk fluor flush flute flyby
flyer foals foams foamy focal focus foggy fogle foils foist folds foley folic folie folio folks
folly fonda fonds fonts foods fools foots footy foray force fords forex forge forgo forks forme
forms forte forth forts forty forum forza fossa fosse fouls found fount fours fovea fowls foxes
foyer foyle frack frail frame franc frank fraud freak freed freer frees frere fresh frets friar
fried fries frill frisk frist frith fritz frizz frock frogs frond front frosh frost froth frown
froze fruit fryer fubar fucks fuddy fudge fuels fugly fugue fully fumed fumes funds fundy fungi
funky funny furor furry furth furze fused fuses fussy futon fuzzy gabba gabby gable gaffe gages
gaily gains galas galea gales galls gally gamba gamed gamer games gamey gamma gammy gamut gandy
gangs ganja gaped gapes garbo garda garth gases gasps gassy gated gates gator gaudy gauge gault
gaunt gauss gauze gauzy gavel gayer gazed gazes gears gecko geeks geeky geese geist gemma genes
genet genie genii genny genoa genre gents genus geode germs geste getup geyer ghats ghazi ghost
ghoul giant giddy gifts gigas gills gilly gilts gimme ginny gipsy girls girly girth given giver
gives gizmo glace glade gland glans glare glass glaze gleam glean glebe glens glial glide glint
glitz gloat globe gloom glory gloss glove glows glued glues gluon glute glyph gnash gnats gnome
goals goats godly goers goeth going golds goldy golem golly gomer goner gongs gonna gonzo goods
goody gooey goofs goofy goold goons goose gored gores gorge gorse gosse goths gotta gouge gourd
gowan gowns goyim grabs grace grade grads graff graft grail grain grama grams grand grant grape
graph grasp grass grate grave gravy grays graze great grebe greed greek green greet greve greys
grice grids grief griff grift grill grime grimy grind grins gripe grips grist grits groan groat
groin groom grope gross grosz group grout grove growl grown grows grubs gruel gruff grump grunt
guano guard guava guess guest guide guild guile guilt guise gulag gulch gules gulls gully gulps
gumbo gummy gundy gunny guppy gurus gusto gusts gusty gutsy gutta guyot gypsy gyros gyrus habit
hacks hades hadji hafiz haiku hails hairs hairy hajji hakim halal hales hallo halls halos halts
halve hamed hames hammy hamza hance hands handy hangs hanks hanky hansa hanse hants happy haram
hards hardy harem hares harks harms harps harpy harry harsh harts hasta haste hasty hatch hated
hater hates hatha haugh hauls haunt haute haven haver haves havoc hawks hazed hazel heads heady
heald heals heaps heard hears heart heath heats heave heavy hecht hedge heels hefty heigh heirs
heist helio helix hello hells helms helps hence henna henny henry herbs herby herds heres heron
heros hertz hexes hicks hider hides highs hight hijab hijra hiked hiker hikes hills hilly hilts
hinds hinge hints hippo hippy hired hires hissy hitch hives hoard hoary hobby hobos hocks hocus
hogan hoist hokey hokum holds holed holes holey holla holly homed homer homes homey homie homme
homos honan honda honed hones honey honks honky honor hooch hoods hoody hoofs hooks hooky hoops
hoots hoped hopes hoppy horas horde horns horny horse horst hosed hoses hosts hotch hotel hotly
hough hound hours house hovel hover howdy howes howls hoyas hoyle hubby huffs huffy huggy hulks
hullo hulls human humic humid humor humph humps humus hunch hunks hunky hunts hurls hurry hurst
hurts husks husky hussy hutch hydra hydro hyena hymen hymns hynde hyoid hyped hyper hypes hythe
icing icons ideal ideas ident idiom idiot idled idler idles idols idyll iftar igloo iliac iliad
ilium image imago imams imbue impel imply inane inbox incur index india indie inept inert infer
infos infra ingle ingot inked inlay inlet inner innit input inset intel inter intra intro ionic
irate irked irons irony isles islet issei issue itchy items ivory izzat jacks jacky jaded jades
jaffa jager jails jakes jambo james jammy janes japan jaunt jawed jazzy jeans jebel jeeps jeers
jeffs jello jelly jenny jerks jerky jerry jesse jesus jetty jeune jewel jibes jiffy jiggy jihad
jimmy jinks jirga jocko jocks johns joins joint joist joked joker jokes jokey jolly jolts jones
jonty joule jours joust jowls judas judge juice juicy jukes julep jumbo jumps jumpy junks junky
junta juror juvie kafir kalam kandy kanga kanji kappa kaput karas karat karma karoo karst karts
kasha kayak kazoo kebab keels keeps kefir kells kelly kelty kendo kents kerns kerry ketch keyed
khadi khaki khans kicks kiddo kiddy kiley kills kilns kilos kilts kinda kinds kings kinks kinky
kiosk kirby kisan kissy kites kitty kiwis klang kluge klutz knack knave knead kneed kneel knees
knell knelt knife knits knobs knock knoll knots known knows koala kohls kondo kooks kooky krabs
kraft kranz kraut krill krona krone kudos kudzu kugel kurta kutch kyles kylie kyrie label labia
labor laced laces lacey lacks laden ladle lagan lager laika laird lairs laity laker lakes lakhs
lakin lamas lambs lamer lames lamia lamps lanai lance lande lands lanes lanky lapel lapin lapis
lapse larch large largo larks larva laser lassi lasso lasts latch later latex lathe latte lauds
laugh laura lavas laver lawns layed layer layin layup lazar leach leads leafs leafy leaks leaky
leans leant leaps leapt learn leary lease leash least leave leben ledge leech leeks leery lefts
lefty legal leger legge leggy legit leman lemma lemon lemur lends lense lento leone leper lesbo
lethe levee level lever levin levis lewis lexis liana liane liang liars libel liber libra libri
licht licks lidar liege liens lieve lifer lifes lifts liger light ligne liked liken likes lilac
liman limbo limbs limes limey limit limos limps lindy lined linen liner lines linga lingo lings
links linky linux lions lipid lippy lisle lists liter lites lithe litho litre lived liven liver
lives livid livre llama llano loach loads loamy loans loath lobby lobed lobes lobos local lochs
locks locos locum locus lodge loess lofts lofty logan logic logie login logon logos lohan loins
lolly lomas loner longa longe longs looks looms loons loony loops loopy loose loots lopes loran
lords lordy lores loris lorry loser loses lossy lotte lotto lotus lough louie louis loupe louse
lousy louts lovat loved lover loves lovey lower lowes lowly lowry loyal lubed lucid lucky lucre
luger lulls lumen lumps lumpy lunar lunch lunge lungs lupin lupus lurch lured lures lurid lurks
lusts lusty lutea lutes lycra lying lymph lynch lyric lysis lysol lytic macaw maces mache machi
macho macon macro madam madge madly madre mafia mafic mages maggs magic magma magus maids maiko
mails mains maire maize major makar maker makes malam malar males malic malik malls malts malty
malwa mamas mamba mambo mamie mamma mammy manas mandi manes manet manga mange mango mangy mania
manic manis manly manna manor manos manse manta manus maple marah march mardy mares marge maria
marks marly maron marri marry marsh marts maser masks mason massa masse massy masts matai match
mated mater mates matey maths matin matte matts matzo mauls mauve maven mavis maxed maxim maxis
mayan maybe mayor mazes meads meals mealy means meant meany meath meats meaty mecca medal media
medic meets melba melds melee melon melts melty memes memos mends mensa menus meows merch mercs
mercy merge merit merle merry mesas meson messy metal meted meter metis metre metro meuse mezzo
micky micra micro midge midst might mikes milch miler miles milfs milks milky mille mills milos
mimes mimic minas mince minds mined miner mines minis minke minks minny minor minos mints minty
minus mired mirth mirza miser mises missa missy mists misty mitch miter mites mitre mitts mixed
mixer mixes mixup moans moats mocha mocks modal model modem modes modus mofos mogul moira moist
molar molds moldy moles molly molto momma mommy monad monde mondo money mongo monks monte month
monty mooch moods moody moons moors moose moped mopey moral moray morel mores moria morne moron
morph morra morro morse moses mosey mossy motel motes moths motif motor motte motto mould moult
mound mount mourn mouse mousy mouth moved mover moves movie mowed mower moxie moyle mucho mucin
mucky mucus muddy mudge mudra muffs mufti muggy mulch mules mulla mulls mummy mumps munch mungo
mural murky murry mused muses mushy music musky musty mutch muted mutes mutha mutts muzzy mylar
myrrh myths nacho nadir nagas nails naira naive naked named names nance nancy nandu nanna nanny
nappa nappy narco nares nasal nasty natal natch natty naval navel nawab nazir nazis nears neath
necks needs needy negro negus neigh nelly nerds nerdy nerve nervy nests never neves newer newly
newts nexus nicer niche nicht nicks nicol nidal niece nifty niger night nihil nines ninja ninth
nippy niqab nisei nitro nitty nixed nizam nkosi nobby noble nobly nodal noddy nodes noirs noise
noisy nomad nomen nomos nonce noobs nooks noose norma norms north nosed noses nosey notch noted
notes nouns novae novas novel novum noyes nubia nudes nudge nudie nuked nukes nulla numbs nurse
nutty nylon nymph nyssa oases oasis oaths obese obeys obits objet occur ocean ocher ochre octal
octet odder oddly odeon odium odors odour offal offed offer often ogres oiled oiler olden older
oldie oleic olive ollie ology ombre omega omens omits onion onset oomph oozed oozes opals opens
opera opine opium opted optic orang orbit orcas order organ oriel ortho orval oscar ostia otaku
other otter ought ouija ounce outdo outed outer outro ovals ovary ovate ovens overs overt ovoid
owing owler owned owner oxbow oxide ozone ozzie paced pacer paces pacey pacha packs pacts paddy
padma padre paean paedo pagan paged pager pages pails pains paint pairs paisa paise pakka paled
paler pales pally palms palsy pampa panda panel panes pangs panic panko pansy panto pants panty
paoli paolo papal papas paper pappy paras pared pares paris parka parks parle parra parry parse
parti parts party paseo pasha passe pasta paste pasts pasty patch pater paths patio patsy patty
pauls pause pavan paved paver paves pawns payed payee payer peace peach peaks peaky pearl pears
peart pease peats peaty peavy pecan pecks pedal pedro peeks peels peeps peers peeve peggy pekin
pelts penal pence penis penna penne penny peons peony peppy perce perch perdu peres peril peris
perks perky perms perps perry perse pervs pervy pesky pesos pesto pests petal petar peter petit
petre petri petty phage pharm phase phlox phone phono phony photo phyla piano picks picky picot
piece piers pieta piety piezo piggy pikes pilaf pilar piled piles pills pilot pimps pinch pined
pines piney pings pinko pinks pinky pinna pinot pinta pinto pints pinup pious piped piper pipes
pique pisco pissy piste pitch pithy pitta pivot pixel pixie pizza place plage plaid plain plait
plane plank plans plant plate plats playa plays plaza plead pleas pleat plebs plied plies plonk
plops plots plows ploys pluck plugs plumb plume plump plums plunk plush poach pocky podge poems
poets point poise poked poker pokes pokey polar poles polio polis polka polls polly polos polyp
ponce ponds pongo ponty pooch poofy pooja pools poops popes poppa poppy porch pored pores porgy
porky porno porta ports posed poser poses posey posit posse posts potts potty pouch pound pours
pouts pouty power prams prana prang prank pratt prawn prays preen preps press prest preys price
prick pricy pride pried prima prime primo print prion prior prise prism privy prize probe probs
prods profs promo proms prone prong proof props prose prost proto proud prove prowl proxy prude
prune psalm psych psyop pubes pubic pubis pucks pudge pudgy puffs puffy puked pukes pulis pulls
pulps pulpy pulse pumas pumps punch punks punky punny punto punts pupae pupal pupil puppy puree
purer purge purrs purse purty pushy pussy putts putty pygmy pylon pyrex quack quads quail quake
quant quark quart quash quasi quays qubit queen queer quell query quest queue quick quiet quiff
quill quilt quine quint quips quire quirk quite quits quota quote quoth rabat rabbi rabid raced
racer races racks radar radii radio radix radon rafts raged rager rages raids rails raine rains
rainy raise rajah rajas raked rakes rally ralph ramen ramin ramis ramps ramus rance ranch rands
randy ranga range rangi ranks rants raped raper rapes rapid rarer rares raspy rasta ratan rated
rater rates ratio ratty raved ravel raven raver raves ravin rayed rayne rayon razed razer razor
reach react reads ready realm reals reams reaps rearm rears rebar rebbe rebel rebus rebut recap
recce recon recto recur recut reddy redid redox redux reeds reedy reefs reeks reels reeve refer
refit regal rehab reign reiki reins relax relay relic reman remit remix renal renew renin rents
repay repel reply repos repro rerun reset resin resto rests retch retro retry reuse revel revie
revue rhine rhino rhone rhyme rials richt ricin ricks rider rides ridge riffs rifle rifts riggs
right rigid rigor riled riles riley rimes rinds rings rinks rinse rioja riots ripen risen riser
rises rishi risks risky rites ritzy rival rivas riven river rives rivet roach roads roams roars
roast robed robes robin robot rocks rocky rodeo roger rogue roker roles rolls roman romeo ronde
rondo ronin roofs rooks rooms roomy roose roost roots rooty roped roper ropes roque roses roshi
rosin rotor rouen rouge rough round rouse route routh routs rover rowan rowdy rowed rowen rower
royal rubes rubin ruble rubus ruddy ruder rueda rugby ruins ruled ruler rules rumba rumen rummy
rumor runes rungs runic runny rupee rural russe rusts rusty saber sabha sabin sable sabot sabra
sabre sacks sacra sadhu sadly safer safes sagas sager sages saggy saheb sahib saiga sails saint
saith sakai saker sakes salad sales salix salle sally salon salop salsa salto salts salty salve
salvo saman samba sambo sammy sands sandy saner sanga sangh sango sansa santo sappy saran saree
sarge sarin saris sasse sassy satay sated sates satin satyr sauce saucy sault sauna saute saved
saver saves savin savor savoy savvy sawed sayed sayer sayid scabs scala scald scale scalp scaly
scamp scams scans scant scapa scape scare scarf scarp scars scary scene scent scion scoff scold
scone scoop scoot scope score scorn scots scour scout scowl scram scrap scree screw scrim scrip
scrub scrum scuba scuff scull scuse seals seams sears seats sebum sects sedan seder sedge sedum
seeds seedy seeks seely seems seeps seers sefer segue seine seize selah sella sells selva semen
semis sends senna senor sense senza sepia sepoy septa serfs serge serif serra serum serve servo
setae seton setup seven sever sewed sewer sexed sexes shack shade shady shaft shake shaky shale
shall shalt shama shame shams shand shank shape shard share shark sharp shaul shave shawl shawn
shays sheaf shear sheds sheen sheep sheer sheet sheik shelf shell sheol shere sheva shied shiel
shift shill shims shine shins shiny ships shire shirk shirt shish shite shits shiva shoal shock
shoes shoji shola shone shook shoot shops shore shorn short shots shout shove shown shows showy
shred shrew shrub shrug shuck shuns shunt shura shush shute shuts shyly sibyl sicko sided sider
sides sidle siege sieur sieve sighs sight sigil sigma signs sikes siler silks silky sills silly
silos silty silva simba since sines sinew singe sings sinks sinus sippy sired siren sires sisal
sissy sitar sited sites sitka situs sixer sixes sixth sixty sized sizes skank skate skeet skein
skene skews skids skied skier skies skiff skill skimp skims skink skins skint skips skirt skits
skool skull skunk slabs slack slade slags slain slake slams slang slant slaps slash slate slats
slaty slave slays sleds sleek sleep sleet slept slice slick slide slime slims slimy sling slink
slips slits sloan slobs sloop sloot slope slosh sloth slots slows slugs slump slums slung slurp
slurs slush sluts slyly smack small smart smash smear smell smelt smile smirk smite smith smits
smock smoke smoky smoot smote smuts snack snafu snags snail snake snaps snare snark snarl snead
sneak sneed sneer snell snide sniff snipe snips snobs snook snoop snore snort snout snows snowy
snubs snuck snuff soaks soaps soapy soars sober socks sodas sodom sofas softy soggy soils sokol
solar solas soled soler soles solid solon solos solus solve sonar songs sonic sonne sonny sooth
sooty sophy soppy sopra sorel sores sorry sorta sorts souls sound soups soupy sours south sowed
sower soyuz space spade spain spake spall spams spank spans spare spark spars spasm spate spats
spawn speak spear speck specs speed speer spell spelt spend spent sperm spews spica spice spicy
spied spiel spies spike spiky spill spilt spina spine spink spins spiny spire spite spits spitz
splat splay split spoil spoke spoof spook spool spoon spoor spore spork sport spots spout spray
spree sprig sprit sprue spuds spunk spurn spurs spurt squad squat squaw squib squid stabs stack
stade staff stage stags staid stain stair stake stale stalk stall stamp stand stang stank staph
stare stark starr stars start stash state stats stave stays stead steak steal steam steed steel
steen steep steer stein stela stele stell stems steno stent steps stern stews stich stick stiff
stile still stilt sting stink stint stipe stirs stoat stock stoic stoke stole stoma stomp stone
stony stood stool stoop stops store stork storm story stott stour stout stove strap straw stray
strep strip strop strum strut stubs stuck studs study stuff stump stung stunk stuns stunt stupa
sturt style suave sucks sucky sucre suede sugar suing suite suits sukuk sulky sully sumac summa
sunna sunny super supes supra surah surat surer surfs surge surly sushi sutra sutta swabs swain
swale swami swamp swamy swank swans swaps swarm swart swash swath swats sways swear sweat swede
sweep sweet swell swept swift swill swims swine swing swipe swire swirl swish swiss swizz swoon
swoop sword swore sworn swung sybil sykes sylva synch syncs synod synth syrah syrup tabby taber
tabla table taboo tabor tache tacit tacks tacky tacos taels taffy taiga taiko tails taint taken
taker takes takin takis tales talks talky tally talon taluk talus tamed tamer tames tammy tanga
tango tangy tanka tanks tanna tansy tanto tapas taped taper tapes tapir taras tardy targa tarot
tarps tarry tarts taser tasks taste tasty tatar tater tatts tatty taunt taupe tawny taxed taxes
taxis taxon teach teams tears teary tease teats techs techy teddy teems teens teeny teeth telco
telex tells telly telos tempo temps tempt tench tends tenet tenon tenor tense tenth tents tepee
tepid terai terms terns terra terry terse tesla testa tests testy tetra texas texts thana thane
thang thank thaws theft thein their thema theme there therm these theta thick thief thigh thine
thing think thins thiol third thong thorn thorp those three threw throb throw thugs thumb thump
thunk thyme tiara tibia ticks ticky tidal tiddy tides tiers tiger tight tikka tilak tilde tiled
tiles tills tilly tilts timed timer times timid timon tinea tines tinge tings tinny tints tippy
tipsy tired tires titan titer tithe title titty tizzy toads toady toast today toddy toils token
tolls tombs tomes tommy tonal toned toner tones toney tonga tongs tonic tonka tonks tonne tools
toons tooth toots topaz topic topos toque torah torch torii toros torso torta torte torts torus
total totem totes touch tough tours touts towed towel tower towie towns toxic toxin toyed trace
track tract trade trail train trait tramp trams trans trant traps trash trawl trays tread treat
trees treks trend tress triad trial tribe trice trick tried trier tries trike trill trims trine
trios tripe trips trist trite trois troll tromp troop trope troth trots trout trove truce truck
truer truly trump trunk truss trust truth tryst tsars tubal tubby tubed tuber tubes tucks tufts
tulip tulle tummy tumor tunas tuned tuner tunes tunic tuple turbo turds turks turns tusks tutor
tutti tutus twain twang twats tweak tweed tween tweet twerk twerp twice twigs twill twine twink
twins twirl twist twits twixt tying tykes tyler typed types typos tyres udder uhuru ulama ulcer
ulema ulnar ultra umami umber umbra ummah umrah unbox uncle uncut under undid undue unfit unify
union unite units unity unlit unmet untie until unwed unzip upend upped upper upset urban urged
urges urine usage users usher using usual usurp usury utter vagal vague vagus vales valet valid
valor value valve vamps vanda vanes vapid vapor vardy varia varna varus vases vault veena veers
vegan vegas veils veins veiny velar venal venom vents venue venus verbs verge verry verse verso
vertu verve vespa vesta vests vetch vexed vials vibes vicar vices vichy video views vigil vigor
villa villi viner vines vinyl viola viper viral vires virus visas visit visor vista vitae vital
vives vivid vixen vlogs vocab vocal vodka vogue voice voids voila voile voles volta volte volts
vomit voted voter votes vouch vowed vowel voxel vroom vulva vying wacko wacky waded wades wafer
wafts waged wager wages wagga wagon wagyu wahoo wails waist waite waits waive waked waken waker
wakes waldo wales walks walla walls wally waltz wands waned wanes wanna wants warby wards wares
warms warns warps warts warty washy wasps waste watch water watts waugh waved waver waves waxed
waxes wazir wazoo weald wears weary weave webby weber wedge weeds weedy weeks weems weeny weeps
weepy weigh weird weirs weise welch welds wells welly welsh welts wench wests whack whale whare
wharf whats wheal wheat wheel whelp where which whiff whigs while whims whine whiny whips whirl
whirr whish whisk whist white whizz whole whoop whore whorl whose whoso wicca wicks widen wider
widow width wield wifes wifey wigan wight wikis wilco wilds wiles wills willy wilts wimps wimpy
wince winch winds windy wined wines wings winks wiped wiper wipes wired wires wised wiser wisps
wispy witch withe witty wives woken wolfs woman wombs women wonga wonky woods woody wooed wools
wooly woops woozy words wordy works world worms wormy worry worse worst worth would wound woven
wowed wrack wraps wrath wreak wreck wrens wrest wring wrist write writs wrong wrote wroth wrung
wryly wurst wushu xenia xenon xerox xylem yacht yager yahoo yanks yards yarns yates yawns yeahs
yearn years yeast yells yelps yerba yield yikes yodel yogic yogis yoked yokes yolks yorks young
yours youse youth yucca yucky yummy yurts zacks zaire zakat zaman zebra zeros zesty zetas zilch
zilla zines zinke zippo zippy zloty zonal zoned zones zooey zooms zorro zulus
`.split(/\s+/).filter(Boolean)
);
for (const word of ANSWERS) VALID.add(word); // every answer is always a valid guess

function isValidGuess(word) {
  return VALID.has(word);
}

function randomAnswer() {
  return ANSWERS[Math.floor(Math.random() * ANSWERS.length)];
}

module.exports = { ANSWERS, VALID, isValidGuess, randomAnswer };
